name: Flutter Test
on:
  push:
    branches: [ BrowseListings ]
  pull_request:
    branches: [ BrowseListings ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.5'

      - name: Get all Flutter Packages
        run: flutter pub get

      - name: Run Flutter Test
        run: flutter test
        
      - name: Upload coverage reports to Codecov
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri https://uploader.codecov.io/latest/windows/codecov.exe 
          -Outfile codecov.exe
          .\codecov.exe -t ${CODECOV_TOKEN}
